spring:
  datasource:
    url: jdbc:mysql://db:3306/weather_tracking?useSSL=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update